name = "SocialNet"
uuid = "9aaaaa74-42fc-4f61-bd2a-fd5ce53f5135"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
